[build]
  publish = "dist"
  command = "npm run build:production"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build:production"

[context.deploy-preview]
  command = "npm run build"
