version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sharenet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ankita10
      MYSQL_DATABASE: sharenet_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sharenet-network

  app:
    build: .
    container_name: sharenet-backend
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:mysql://mysql:3306/sharenet_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=ankita10
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,https://sharex-net.vercel.app
    ports:
      - "8080:8080"
    networks:
      - sharenet-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  sharenet-network:
    driver: bridge
